name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"

      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: |
          luarocks install busted
          luarocks install luacov
          luarocks install luacov-coveralls
          luarocks install luafilesystem

      - name: Run Tests
        env:
          LUA_PATH: "./lua/?.lua;./lua/?/init.lua;./?.lua;$LUA_PATH"
          GITPILOT_TEST: "1"
        run: |
          busted -v --coverage test/gitpilot/features/

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          luacov-coveralls -v
